In [18]:
import numpy
n=numpy.arange(27000)

In [7]:
n

array([    0,     1,     2, ..., 26997, 26998, 26999])

In [8]:
print(n)

[    0     1     2 ... 26997 26998 26999]


In [14]:
n.reshape(3,3,3000)

array([[[    0,     1,     2, ...,  2997,  2998,  2999],
        [ 3000,  3001,  3002, ...,  5997,  5998,  5999],
        [ 6000,  6001,  6002, ...,  8997,  8998,  8999]],

       [[ 9000,  9001,  9002, ..., 11997, 11998, 11999],
        [12000, 12001, 12002, ..., 14997, 14998, 14999],
        [15000, 15001, 15002, ..., 17997, 17998, 17999]],

       [[18000, 18001, 18002, ..., 20997, 20998, 20999],
        [21000, 21001, 21002, ..., 23997, 23998, 23999],
        [24000, 24001, 24002, ..., 26997, 26998, 26999]]])

In [25]:
n=numpy.asarray([[0,     1,     2],
        [ 3],
        [ 6]])
n

array([list([0, 1, 2]), list([3]), list([6])], dtype=object)

In [27]:
type(n)

numpy.ndarray

In [2]:
import cv2

In [11]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
cv2.imwrite( "newsmallgray.png", im_g)

True

In [8]:
a=[1,2,3]

In [9]:
a[0:2]
a

[1, 2, 3]

In [13]:
im_g[0:2,2:3]

array([[104],
       [255]], dtype=uint8)

In [15]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [16]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [34]:
ims=numpy.hstack((im_g,im_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [36]:
ims=numpy.vstack((ims,ims))
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]
 [187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [39]:
lst=numpy.hsplit(ims,2)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [44]:
print(lst[1])

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
